version: '2'

services:

  docser:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - docser_files:/usr/src/app:rw

volumes:
  docser_files: